# Generated by Django 5.1.1 on 2024-10-02 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
